### ISSUE TITLE
[BUG] Possible memory leak

### ISSUE THREAD

**Issue by James-Large** [sktime/sktime-dl#1]
Copied over/adapted from the initial PR to sktime:

There seems to be some kind of memory leak, specifically in those models that do some form of internal parameter tuning MCNN, and TLENET (perhaps the others too, however the rate of the leak would seem to be negligible in these cases). Running a single model on a single dataset seems to be fine. Running many in a single execution eventually leads to an error with very little explanation, but which is almost certainly due to an unexpected/unintended OOM, i.e. a leak. 

Some links so far into my investigation, but again this requires further investigation over time to fix: 

* Old, but might be a problem with keras itself and how it handles it's tf sessions
    * [1](https://github.com/keras-team/keras/issues/2102), where downgrading Keras may fix: 
        * [2](https://github.com/keras-team/keras/issues/2102#issuecomment-410823700)
        * [3](https://github.com/keras-team/keras/issues/2102#issuecomment-418888790)
* Switching to theano or downgrading is an option... 
* Might also be a problem not with keras specifically, but running keras within pycharm...
    * [4](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000015484-exit-code-1073741819-0xC0000005-)
    * [5](https://stackoverflow.com/questions/46745523/keras-model-failing-to-compile-exit-code-1073741819-0xc0000005)
    * leading to... [6](https://youtrack.jetbrains.com/issue/PY-17069)
* Running multiple MCNNs in pycharm leads to errors/exit codes, however running from e.g. anaconda prompt looks like it leaks memory much slower, but still eventually fails

**Comment by hfawaz** [comment]
I think I used to solve this problem with the following [line](https://github.com/hfawaz/dl-4-tsc/blob/9d54e6e11f22a40f2eea06a4db87099e153c0f15/classifiers/resnet.py#L134).

**Comment by James-Large** [comment]
Hey Hassan

Yeah saw that, we tried various combinations of these e.g. [here](https://github.com/uea-machine-learning/sktime-dl/blob/73f5ba9a55c38a8dbcaeb9cec50fff032ed88d68/sktime_dl/classifiers/deeplearning/_mcnn.py#L423) but seemingly little luck. 
 ```
del model
gc.collect()
keras.backend.clear_session()
```
They're all fine to run to run to completion (i.e. fit/predict) on all the datasets I've tested on at least once. You run all your experiments distributed right? 

Haven't looked at actually solving this since initial implementation a month ago, but it may well be some problem with running keras in pycharm as per one of the links in OP

**Comment by hfawaz** [comment]
Hey James, 

Yeah I run them distributed, but I haven't encountered any problem when running on a single GPU. 
However, I should note that I have never used PyCharm to train, I use anaconda env with a Quadro P6000. 

Best,

**Comment by James-Large** [comment]
Update to this, I believe passive updates via tensorflow in newer versions have fixed this. Older versions (oldest now usable is tf1.9) may still experience this, but I believe it was under specific circumstances, and only if building multiple models in a single execution, which is a rare and avoidable scenario in research experimentation.

Shall close
