### ISSUE TITLE
[BUG] Examples don't run

### ISSUE THREAD

**Issue by h3dema** [sktime/sktime-dl#123]
**Describe the bug**
When trying to run the examples in the /examples folder.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-f9175d24a920> in <module>
      5 from sklearn.model_selection import GridSearchCV
      6 from sktime.datasets import load_gunpoint, load_italy_power_demand
----> 7 from sktime_dl.deeplearning import CNNClassifier
      8 
      9 sns.set_style('whitegrid')

ModuleNotFoundError: No module named 'sktime_dl.deeplearning'

**To Reproduce**
1. Clone the repository
2. Install the dependencies and install sktime-dl
3. Open univariate_time_series_classification.ipynb
4. Execute the first cell with code

```python
```

**Expected behavior**
Apparently sktime_dl don't have this module anymore, which was replaced by
sktime_dl.classification and sktime_dl.regression.

**Additional context**

**Versions**
absl-py-0.15.0 flatbuffers-1.12 gast-0.4.0 grpcio-1.34.1 h5py-3.5.0 keras-2.5.0rc0 keras-nightly-2.5.0.dev2021032900 opt-einsum-3.3.0 sktime-0.7.0 sktime-dl-0.2.0 tensorboard-2.7.0 tensorboard-data-server-0.6.1 tensorflow-2.5.0 tensorflow-addons-0.14.0 tensorflow-estimator-2.5.0 typeguard-2.13.0

Linux-4.15.0-151-generic-x86_64-with-debian-buster-sid
Python 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50) 
[GCC 7.5.0]
NumPy 1.21.3
SciPy 1.4.1
sktime 0.7.0
sktime_dl 0.2.0

**Comment by fkiraly** [comment]
obsolete - example notebooks are now in `sktime`, and regularly tested that they run
