### ISSUE TITLE
Examples/documentation

### ISSUE THREAD

**Issue by James-Large** [sktime/sktime-dl#26]
It's about time an example or two and perhaps deeper documentation is made, I reckon

Examples should likely just mirror https://github.com/alan-turing-institute/sktime/tree/master/examples in location/structure

Example 1: probably mirroring univariate_time_series_classification.ipynb, including regression too 

Example 2: examples with more keras-focused things (separate from base sktime): model saving/loading, callbacks when those come back in, maybe some tensorboard things

etc. 

Full on documentation and e,g, github pages are things that to me personally would be great if they existed, but I'm likely not going to do it any time soon. The majority of what you might expect for sktime-dl is covered by base sktime anyway.

**Comment by Withington** [comment]
Definitely. I started [example 1](https://github.com/Withington/sktime-dl/blob/local_dev/examples/univariate_time_series_classification.ipynb) a while back. I could polish that up at the end of this week.
