### ISSUE TITLE
macOS and Windows environments on travis tests

### ISSUE THREAD

**Issue by James-Large** [sktime/sktime-dl#28]
For completeness, these test envs should be added too, however they would be non-trivial.

Versioning between operating systems is of course one issue. See [here](https://www.tensorflow.org/install/source#cpu_2), as of writing macOS supports up to tf 2.0, but not 2.1 (on cpu, that is) 

Windows should be able to support any version, but windows envs on travis are less feature-rich. It should be possible in principle, https://docs.travis-ci.com/user/reference/windows/

Alternatively, docker/equivalent environments could be setup and used within the travis tests to alleviate some of these problems. #27 

Investigation into other open-source projects and how they do multi-os tests would be good

**Comment by mloning** [comment]
Closed by #50
