### ISSUE TITLE
TapNet implementation

### ISSUE THREAD

**Issue by james-large** [sktime/sktime-dl#48]
Tapnet is a strong contender for MTSC

implementation in pytorch: 
https://github.com/kdd2019-tapnet/tapnet

**Comment by MJFlynn** [comment]
Hey James
I'm just getting set-up with sktime-dl. But i'll go ahead and attempt to port this into toolkit. I'll report back here with progress.

**Comment by fkiraly** [comment]
successfully closed as it was implemented in `sktime-dl`, then migrated to `sktime`
