### ISSUE TITLE
Use `check_random_state` for handling random seeds

### ISSUE THREAD

**Issue by mloning** [sktime/sktime-dl#53]
**Is your feature request related to a problem? Please describe.**
Currently we do not have a consistent way of handling random seeds.

**Describe the solution you'd like**
 I suggest to use scikit-learn's [`check_random_state`](https://scikit-learn.org/stable/modules/generated/sklearn.utils.check_random_state.html) function and to rename all input arguments to `random_state` for compatibility with scikit-learn.

**Comment by TonyBagnall** [comment]
@mloning I've discussed this with the group, and the consensus is that seeding keras/tensor flow to allow reproducible/deterministic experiments is not really feasible or at least not worthwhile. Everything is threaded and GPU based. I think it better to offer no seeding than seeding that doesnt work.

**Comment by fkiraly** [comment]
obsolete
