### ISSUE TITLE
Add flaky for forecasting tests

### ISSUE THREAD

**Issue by mloning** [sktime/sktime-dl#56]
Some of the forecasting tests fail sporadically with nan values, we should make use of flaky. 

Seems to happen predominantly on Python 3.6 with TensorFlow 1.19.

For logs with failure, see: https://dev.azure.com/mloning/sktime-dl/_build/results?buildId=234&view=logs&j=2f3623ac-aacd-5154-10a9-b0df3a28b931&t=bb40cb68-473e-5041-6b6e-d12fea788451

**Comment by James-Large** [comment]
This was found again in #64, and somewhat hack-ily resolved by giving the offending network (MCDCNNRegressor) extra epochs to learn from and hopefully produce non-NaN predictions. If this is a problem again sporadically in the future, revisit this option.

**Comment by TonyBagnall** [comment]
close for now for restructure, feel free to reopen once it is stable again
