### ISSUE TITLE
will your cod work  when data is mixer of continues and categorical variables for each time sample?

### ISSUE THREAD

**Issue by Sandy4321** [sktime/sktime-dl#58]
will your cod work  when data is mixer of continues and categorical variables for each time sample?
for example data samples are
time t1: red , 0.4 , big , low, 234
time t2: green, 0.8, big, high, 12
time t3: green, 0.1, small, low, 34
etc

**Comment by mloning** [comment]
@Sandy4321 please clarify your questions, I don't understand what you mean.

**Comment by Sandy4321** [comment]
Let's simplify
Will you code work for multivariate categorical time series?
