### ISSUE TITLE
sktime-dl examples?

### ISSUE THREAD

**Issue by jmrichardson** [sktime/sktime-dl#60]
**Is your feature request related to a problem? Please describe.**
Hi, are there any example notebooks or documentation specifically for sktime-dl? 

**Describe the solution you'd like**
Any pointers or tutorials

Thank you :)

**Comment by mloning** [comment]
Hi, not at the moment, but the sktime-dl deep learning classifiers should work with the classification tutorial notebooks in sktime (at least the current sktime-dl dev branch, there are still some updates pending). 

We also have some code to run comparative benchmarking experiments [here](https://github.com/sktime/sktime-dl/blob/master/sktime_dl/experimental/reproductions.py) if that helps. 

But we'd be happy to include some if you're interested in writing them?

**Comment by wangyida** [comment]
@mloning Does sktime-dl completely depends on tensorflow keras backends or including pytorch as well? I found that existed examples are mostly based on tensorflow 2.0

**Comment by mloning** [comment]
Hi @wangyida, for now tensorflow and eras
