### ISSUE TITLE
Forecasting reduction capabilities/tests

### ISSUE THREAD

**Issue by James-Large** [sktime/sktime-dl#64]
Had a quick look into the forecasting wrapper problem from sktime 0.4, brought up in PR #59, referenced now in #47.

Ultimately the problem is that the reduction strategy passes the data to the -dl regressor as numpy arrays (even if pd.Series are given to the ReducedRegressionForecaster.fit()), which gets flagged as illegal by sktime.utils.validation.series_as_features.check_X_y, which is always checked because input_checks=True is the default in the -dl regressor's fit() 

The test ([currently commented out on dev](https://github.com/sktime/sktime-dl/blob/dev/sktime_dl/deeplearning/tests/test_regressors.py#L40)) basically follows the code the the forecasting example from base sktime, which uses the KNNRegressor from sklearn, which  of course doesn't run with the check_X_y

This comes down to what is the convention now in base sktime in terms of data input/throughput. Looking at a couple of the classifiers in base sktime, [e.g.](https://github.com/alan-turing-institute/sktime/blob/master/sktime/classification/interval_based/_tsf.py#L117), the checks are applied unconditionally, so presumably regression reduced to classification runs into the same problem? 

1. We relax the dataframe requirement (which technically under the current code is only a requirement if input_checks=True, which again it is by default) and allow np arrays
2. We change the default to input_checks=False
3. This is a problem in the reduction strategy in that it should be passing around dataframes
4. This is a problem in the reduction strategy in that it should try to pass the keyword arg input_checks=False to the base regressor's fit, under the assumption that it produces data (via the splitter etc.) that is suitable anyway and doesn't need checking, [e.g. here ](https://github.com/alan-turing-institute/sktime/blob/master/sktime/forecasting/compose/_reduce.py#L307)
5. ?? 

Thoughts?

**Comment by mloning** [comment]
There's a separate reduction strategy for going from forecasting to time series regression, so this works: 

```python
from sktime.datasets import load_airline
from sktime.forecasting.compose import RecursiveTimeSeriesRegressionForecaster
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime_dl.deeplearning import MLPRegressor
import numpy as np

y = load_airline()
y_train, y_test = temporal_train_test_split(y, test_size=10)
fh = np.arange(1, len(y_test) + 1)  # forecasting horizona

regressor = MLPRegressor(nb_epochs=100)
forecaster = RecursiveTimeSeriesRegressionForecaster(regressor=regressor)
forecaster.fit(y_train)
y_pred = forecaster.predict(fh)
```
The reduction wrapper should probably raise more informative error messages. 

Will open a PR to fix this in the tests.

**Comment by James-Large** [comment]
Aha, that makes more sense. Should have seen that myself if I wasn't blindly following class links around and took a wider field of view

**Comment by James-Large** [comment]
Do believe is is resolved under #65m closing
