### ISSUE TITLE
Update examples notebooks to support sktime 0.4.1

### ISSUE THREAD

**Issue by Withington** [sktime/sktime-dl#66]
**Describe the bug**
examples/*ipynb are not working in dev branch with sktime 0.4.1

**Comment by Withington** [comment]
@mloning Is sktime Tabularizer working correctly? This fails `Xt = Tabularizer().transform(X)` with `This instance of Tabularizer has not been fitted yet; please call `fit` first.`

**Comment by mloning** [comment]
It should be
```python
Xt = Tabularizer().fit_transform(X)
```
We follow scikit-learn's logic where you have to call fit first (even if fit basically doesn't do anything as in this case)
