### ISSUE TITLE
[BUG] ImportError: cannot import name 'tabularise' from 'sktime.utils.data_container'

### ISSUE THREAD

**Issue by aug2uag** [sktime/sktime-dl#70]
**Describe the bug**
Looks like there's digression between sktime and sktime-dl with some deprecated methods in sktime.utils.data_container

**To Reproduce**
A fresh installation of sktime-dl from `dev` branch with standard pip install sktime yielded the following error:
```
ImportError: cannot import name 'tabularise' from 'sktime.utils.data_container'
```

in sktime_dl.utils._data line 6
```python
from sktime.utils.data_container import tabularise, nested_to_3d_numpy
```

**Expected behavior**
sktime.utils.data_container deprecated `tabularize`, there isn't a method named `tabularise`:

```python
@deprecated("Please use `from_nested_to_2d_numpy` instead.")
def tabularize(X, return_array=False):
    return from_nested_to_2d_array(X, return_array)
```

There also seems to be a method name change, `nested_to_3d_numpy` doesn't exist, instead there's `from_nested_to_3d_numpy`.

**Additional context**
I commented out the block on Python 3.8 in setup.py, why is it there? Py3.8 seems to run Ok

**Versions**
macOS-10.15.6-x86_64-i386-64bit
Python 3.8.2 (default, Oct 14 2020, 17:06:12) 
[Clang 11.0.3 (clang-1103.0.32.62)]
NumPy 1.18.5
SciPy 1.5.3
sktime 0.4.3
sktime_dl 0.2.0

</details>

**Comment by mloning** [comment]
Hi @aug2uag, sktime-dl is lagging behind a bit at the moment, we still need to integrate some changes to catch up with the sktime base package. 

We renamed that function, `from sktime.utils.data_container import from_nested_to_2d_array` should work with the newest sktime release.

**Comment by aug2uag** [comment]
sounds good, thanks for the info
