### ISSUE TITLE
[BUG] Problem with sktime-dl installation; cannot import e.g. sktime_dl.deeplearning

### ISSUE THREAD

**Issue by saltazaur** [sktime/sktime-dl#74]
**Describe the bug**

I create a new Conda env:  `conda create -n sktime-dl python=3.6` then run: `pip install sktime-dl` but than when I try to `from sktime_dl.deeplearning import CNNClassifier` Python cannot find `sktime_dl.deeplearning`. 

I also tried to install development version of sktime-dl but the package cannot be installed as there are NumPy and h5py conflicts (Tensorflow requires older numpy and h5py). I also tried to install required NumPy and h5py before running `pip install .`, but it doesn't help.

**To Reproduce**

```
conda create -n sktime-dl python=3.6
conda activate sktime-dl
pip install sktime-dl
```
```python
from sktime_dl.deeplearning import CNNClassifier
```

**Expected behavior**

I can run: `from sktime_dl.deeplearning import CNNClassifier` 
and I can run locally Jupyter Notebooks from `examples`.

**Additional context**

**Versions**
Linux-4.19.128-microsoft-standard-x86_64-with-debian-buster-sid
Python 3.6.11 | packaged by conda-forge | (default, Aug  5 2020, 20:09:42)
NumPy 1.18.5
SciPy 1.5.4
sktime 0.4.3
sktime_dl 0.1.0

**Comment by mloning** [comment]
Hi @saltazaur, thanks for raising the issue!

Does `sktime_dl.classifiers.deeplearning import CNNClassifier` work instead with `pip install sktime_dl`?

We changed the module structure on master but haven't made a new release yet. There are a number of things that need to get fixed before we can make a new release, but we haven't had time to work on it yet.

**Comment by saltazaur** [comment]
Hi,
sorry, but I didn't understand your question :) Do you want me to try to install `sktime_dl` from Github - master branch? Or should I just wait for the new release and than try?

**Comment by mloning** [comment]
Ah sorry, I should have been clearer. Given the unfinished state of the current master branch, I'd `pip install sktime-dl`, effectively installing `v0.1.0`.

With that you should be able to run `sktime_dl.classifiers.deeplearning import CNNClassifier`. 

If you run into the `tabularise` import error, see if you can avoid that by pinning `sktime` to a previous version, either `v0.4.2` or `v0.4.1` I hope.

**Comment by saltazaur** [comment]
Hi,
I tried `pip install sktime-dl` with `sktime==v0.4.2` (and `sktime==v0.4.1`), `h5py==2.10.0`, `numpy==1.18.0` but I still can't import `sktime_dl.deeplearning`.
I did the same steps for `sktime-dl` from the repo v0.1.0 (`pip install .`), but when I try to `from sktime_dl.deeplearning import CNNClassifier` I get `ImportError: cannot import name 'CNNClassifier'`.

**Comment by saltazaur** [comment]
Maybe for now I should try `sktime-dl` in Docker.

**Comment by mloning** [comment]
With `sktime-dl` `v0.1.0` you need to use `sktime_dl.classifiers.deeplearning import CNNClassifier` I believe. 

Take a look at the code structure by checking out the tag of that version: [`v0.1.0`](https://github.com/sktime/sktime-dl/tree/v0.1.0).

**Comment by saltazaur** [comment]
Ok, make sense, byt than I run into `ImportError: cannot import name 'check_X_y'` :) which looks similar to  [#12 ](https://github.com/sktime/sktime-dl/issues/12)

**Comment by mloning** [comment]
Yes, so what you now also have to do is downgrade your `sktime` installation, hopefully `sktime==v0.4.1` works.

**Comment by saltazaur** [comment]
Hi,
no, it doesn't work either with `sktime==v0.4.0` - `sktime==v0.4.3`.
Is it the issue you could reproduce? or is it specific to my setup?

**Comment by mloning** [comment]
Ah this is frustrating! I had a quick look but couldn't get it work either. I'm not really sure what's going on because it was working at some point in the past!

**Comment by saltazaur** [comment]
I would love to come back once `sktime-dl` works. The library and models look so promising! I will monitor the repo :) 👍

**Comment by SatyamGaba** [comment]
@saltazaur Sometimes I make the silly mistake of running code from a wrong path. Just verify once that is not the case with you.

**Comment by mloning** [comment]
@SatyamGaba have you been able to get it to work?

**Comment by moat335a** [comment]
Hi:)
Like said by other users it looks like a really promising library to us in TSC projects, I've tried to use it as well but got exactly the same error.  tried different possible solutions like ones described above but still doesnt seem to work.

**Comment by mloning** [comment]
Hi @moat335a, we're currently stretched pretty thin with the development of base sktime - we'd appreciate someone to attempt to update sktime-dl to be in line with base sktime to fix these errors.

**Comment by talhaanwarch** [comment]
This issue is related to the installation of this package. 
If I install the developmental version, I installed `0.1.0` version via these commands
```
git clone https://github.com/sktime/sktime-dl.git
cd sktime-dl
git checkout dev
git pull origin dev
pip install .```
If I directly add the package to the path after downloading it show `0.2.0`
```
import sys
sys.path.insert(0, "D:\\github_repos\\sktime-dl")```

**Comment by oustella** [comment]
@mloning I'd love to help but would appreciate some directions. I found `check_X_y` in version 0.4.x of sktime, so you were right. The problem seems to be that sklearn_dl refers to it as `from sktime.utils.validation import check_X_y`, whereas it should be under `from sktime.utils.validation.series_as_features import check_X_y`. Should I create a pull request in the 0.1.0 version of sktime_dl for that line? If so, is the version on PyPI gets automatically updated? Thank you.

**Comment by mloning** [comment]
Hi @oustella - yes, I think this is the first step. There may be other things from sktime that have changed. It will require some debugging I believe. But I should have some time these days to help with that if you make a start!

**Comment by oustella** [comment]
@mloning I can do that!
