### ISSUE TITLE
[BUG] ImportError: cannot import name 'tabularise'

### ISSUE THREAD

**Issue by belinakim** [sktime/sktime-dl#76]
**Describe the bug**

I cannot import any classifier or regressor from sktime_dl.deeplearing! I got  ImportError: cannot import name 'tabularise'
**To Reproduce**

```python
conda create -n sktime-dl python=3.6
conda activate sktime-dl
git clone https://github.com/sktime/sktime-dl.git
cd sktime-dl
git checkout dev
git pull origin dev
pip install .

from sktime_dl.deeplearning import CNNClassifier
```

**Expected behavior**

**Additional context**

**Versions**
<details>

Darwin-19.6.0-x86_64-i386-64bit
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 17:50:39) 
[GCC Clang 10.0.0 ]
NumPy 1.19.4
SciPy 1.5.4
sktime 0.4.3
sktime_dl 0.2.0

</details>

**Comment by mloning** [comment]
Hi @belinakim - we're having some issues with sktime-dl at the moment, also see #74. Hopefully we'll find some time to fix these issues soon - but help is appreciated!
