### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'sktime.utils.data_container'

### ISSUE THREAD

**Issue by talhaanwarch** [sktime/sktime-dl#79]
I installed the development version of sktime along with pip version which is `0.5.0`
Sktime-dl development version is installed

I am using colab with following settings
Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]
NumPy 1.19.4
SciPy 1.4.1
sktime 0.5.0
sktime_dl 0.2.0

I am getting following error
`ModuleNotFoundError: No module named 'sktime.utils.data_container'`

**Here is the solution**
At this file
`sktime_dl/utils/_data.py`

change
`from sktime.utils.data_container import tabularise, nested_to_3d_numpy`
to
`from sktime.utils.data_processing import from_nested_to_2d_array, from_nested_to_3d_numpy`
and change

`from sktime.utils.validation.series_as_features import check_X, check_X_y`
to
`from sktime.utils.validation.panel import check_X, check_X_y`

**Comment by mloning** [comment]
Hi @talhaanwarch - thanks for raising this issue, this is due to the new sktime release, it's now in `sktime.data_io`

**Comment by nocciolate** [comment]
I'm a beginner, but the from_nested_to_2d_array cannot take an argument "return_array=True". If you remove this, then it returns a Dataframe. What seems to work for me is basically returning just the values:

`from_nested_to_2d_array(X).values`

**Comment by mloning** [comment]
The argument name may have changed too, you can now use: `from_nested_to_2d_array(X, return_numpy=False)`
