### ISSUE TITLE
Multivariate classification capabilities

### ISSUE THREAD

**Issue by James-Large** [sktime/sktime-dl#9]
Currently networks only accept univariate input data, should open up this restriction to allow multivariate data. Should for the most part just involve some numpy data wrangling and updating the input shape

**Comment by mloning** [comment]
I'd say given the feedback (thumbs, hearts and rockets), this may be a good next step, also since we don't have many bespoke multivariate methods in base sktime.

**Comment by Withington** [comment]
Yes, multivariate would be good. I added a multivariate test using load_basic_motions and started looking at the [data wrangling](https://github.com/Withington/sktime-dl/blob/mcdcnn_test/sktime_dl/utils/data_container.py). Does the data wrangling need to be put into a [sktime Transformer](https://github.com/alan-turing-institute/sktime/blob/master/sktime/transformers/compose.py) class?

**Comment by James-Large** [comment]
Multivariate handling added back in #34
